"""empty message

Revision ID: 61a2854387b8
Revises: dec3343dcb08
Create Date: 2020-06-09 09:44:49.427807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a2854387b8'
down_revision = 'dec3343dcb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('update todos set completed = False where completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
